// ==============================================================================
// OFFICIAL CHAMPIONSHIP CATEGORY CONFIGURATION
// World Taekwondo (WT) Standard Weight Categories & Kukkiwon Regulations
// ==============================================================================

import { Category } from "@/types/registration";

export const INITIAL_CATEGORIES: Omit<Category, "id" | "championship_id">[] = [
  // ----------------------------------------------------------------------------
  // KYORUGI (SPARRING) - SENIOR MALE (Age 17+) - Official World Taekwondo
  // ----------------------------------------------------------------------------
  {
    code: "KY-SEN-M-U54",
    name: "Senior Male Under 54kg (Finweight)",
    discipline: "KYORUGI",
    division: "SENIOR",
    gender: "MALE",
    min_age: 17,
    max_age: 65,
    min_weight: 45.0,
    max_weight: 54.0,
    belt_requirement: "1ST_DAN_ABOVE",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 1,
    is_active: true,
  },
  {
    code: "KY-SEN-M-U58",
    name: "Senior Male Under 58kg (Flyweight)",
    discipline: "KYORUGI",
    division: "SENIOR",
    gender: "MALE",
    min_age: 17,
    max_age: 65,
    min_weight: 54.1,
    max_weight: 58.0,
    belt_requirement: "1ST_DAN_ABOVE",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 2,
    is_active: true,
  },
  {
    code: "KY-SEN-M-U63",
    name: "Senior Male Under 63kg (Bantamweight)",
    discipline: "KYORUGI",
    division: "SENIOR",
    gender: "MALE",
    min_age: 17,
    max_age: 65,
    min_weight: 58.1,
    max_weight: 63.0,
    belt_requirement: "1ST_DAN_ABOVE",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 3,
    is_active: true,
  },
  {
    code: "KY-SEN-M-U68",
    name: "Senior Male Under 68kg (Featherweight)",
    discipline: "KYORUGI",
    division: "SENIOR",
    gender: "MALE",
    min_age: 17,
    max_age: 65,
    min_weight: 63.1,
    max_weight: 68.0,
    belt_requirement: "1ST_DAN_ABOVE",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 4,
    is_active: true,
  },
  {
    code: "KY-SEN-M-U74",
    name: "Senior Male Under 74kg (Lightweight)",
    discipline: "KYORUGI",
    division: "SENIOR",
    gender: "MALE",
    min_age: 17,
    max_age: 65,
    min_weight: 68.1,
    max_weight: 74.0,
    belt_requirement: "1ST_DAN_ABOVE",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 5,
    is_active: true,
  },
  {
    code: "KY-SEN-M-U80",
    name: "Senior Male Under 80kg (Welterweight)",
    discipline: "KYORUGI",
    division: "SENIOR",
    gender: "MALE",
    min_age: 17,
    max_age: 65,
    min_weight: 74.1,
    max_weight: 80.0,
    belt_requirement: "1ST_DAN_ABOVE",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 6,
    is_active: true,
  },
  {
    code: "KY-SEN-M-U87",
    name: "Senior Male Under 87kg (Middleweight)",
    discipline: "KYORUGI",
    division: "SENIOR",
    gender: "MALE",
    min_age: 17,
    max_age: 65,
    min_weight: 80.1,
    max_weight: 87.0,
    belt_requirement: "1ST_DAN_ABOVE",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 7,
    is_active: true,
  },
  {
    code: "KY-SEN-M-O87",
    name: "Senior Male Over 87kg (+87kg Heavyweight)",
    discipline: "KYORUGI",
    division: "SENIOR",
    gender: "MALE",
    min_age: 17,
    max_age: 65,
    min_weight: 87.1,
    max_weight: 140.0,
    belt_requirement: "1ST_DAN_ABOVE",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 8,
    is_active: true,
  },

  // ----------------------------------------------------------------------------
  // KYORUGI (SPARRING) - SENIOR FEMALE (Age 17+) - Official World Taekwondo
  // ----------------------------------------------------------------------------
  {
    code: "KY-SEN-F-U46",
    name: "Senior Female Under 46kg (Finweight)",
    discipline: "KYORUGI",
    division: "SENIOR",
    gender: "FEMALE",
    min_age: 17,
    max_age: 65,
    min_weight: 38.0,
    max_weight: 46.0,
    belt_requirement: "1ST_DAN_ABOVE",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 10,
    is_active: true,
  },
  {
    code: "KY-SEN-F-U49",
    name: "Senior Female Under 49kg (Flyweight)",
    discipline: "KYORUGI",
    division: "SENIOR",
    gender: "FEMALE",
    min_age: 17,
    max_age: 65,
    min_weight: 46.1,
    max_weight: 49.0,
    belt_requirement: "1ST_DAN_ABOVE",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 11,
    is_active: true,
  },
  {
    code: "KY-SEN-F-U53",
    name: "Senior Female Under 53kg (Bantamweight)",
    discipline: "KYORUGI",
    division: "SENIOR",
    gender: "FEMALE",
    min_age: 17,
    max_age: 65,
    min_weight: 49.1,
    max_weight: 53.0,
    belt_requirement: "1ST_DAN_ABOVE",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 12,
    is_active: true,
  },
  {
    code: "KY-SEN-F-U57",
    name: "Senior Female Under 57kg (Featherweight)",
    discipline: "KYORUGI",
    division: "SENIOR",
    gender: "FEMALE",
    min_age: 17,
    max_age: 65,
    min_weight: 53.1,
    max_weight: 57.0,
    belt_requirement: "1ST_DAN_ABOVE",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 13,
    is_active: true,
  },
  {
    code: "KY-SEN-F-U62",
    name: "Senior Female Under 62kg (Lightweight)",
    discipline: "KYORUGI",
    division: "SENIOR",
    gender: "FEMALE",
    min_age: 17,
    max_age: 65,
    min_weight: 57.1,
    max_weight: 62.0,
    belt_requirement: "1ST_DAN_ABOVE",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 14,
    is_active: true,
  },
  {
    code: "KY-SEN-F-U67",
    name: "Senior Female Under 67kg (Welterweight)",
    discipline: "KYORUGI",
    division: "SENIOR",
    gender: "FEMALE",
    min_age: 17,
    max_age: 65,
    min_weight: 62.1,
    max_weight: 67.0,
    belt_requirement: "1ST_DAN_ABOVE",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 15,
    is_active: true,
  },
  {
    code: "KY-SEN-F-U73",
    name: "Senior Female Under 73kg (Middleweight)",
    discipline: "KYORUGI",
    division: "SENIOR",
    gender: "FEMALE",
    min_age: 17,
    max_age: 65,
    min_weight: 67.1,
    max_weight: 73.0,
    belt_requirement: "1ST_DAN_ABOVE",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 16,
    is_active: true,
  },
  {
    code: "KY-SEN-F-O73",
    name: "Senior Female Over 73kg (+73kg Heavyweight)",
    discipline: "KYORUGI",
    division: "SENIOR",
    gender: "FEMALE",
    min_age: 17,
    max_age: 65,
    min_weight: 73.1,
    max_weight: 120.0,
    belt_requirement: "1ST_DAN_ABOVE",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 17,
    is_active: true,
  },

  // ----------------------------------------------------------------------------
  // KYORUGI (SPARRING) - JUNIOR MALE (Age 15-17) - Official World Taekwondo
  // ----------------------------------------------------------------------------
  { code: "KY-JUN-M-U45", name: "Junior Male Under 45kg (Fin)", discipline: "KYORUGI", division: "JUNIOR", gender: "MALE", min_age: 15, max_age: 17, min_weight: 35.0, max_weight: 45.0, belt_requirement: "1ST_POOM_ABOVE", registration_fee: 2500, max_participants: 64, display_order: 20, is_active: true },
  { code: "KY-JUN-M-U48", name: "Junior Male Under 48kg (Fly)", discipline: "KYORUGI", division: "JUNIOR", gender: "MALE", min_age: 15, max_age: 17, min_weight: 45.1, max_weight: 48.0, belt_requirement: "1ST_POOM_ABOVE", registration_fee: 2500, max_participants: 64, display_order: 21, is_active: true },
  { code: "KY-JUN-M-U51", name: "Junior Male Under 51kg (Bantam)", discipline: "KYORUGI", division: "JUNIOR", gender: "MALE", min_age: 15, max_age: 17, min_weight: 48.1, max_weight: 51.0, belt_requirement: "1ST_POOM_ABOVE", registration_fee: 2500, max_participants: 64, display_order: 22, is_active: true },
  { code: "KY-JUN-M-U55", name: "Junior Male Under 55kg (Feather)", discipline: "KYORUGI", division: "JUNIOR", gender: "MALE", min_age: 15, max_age: 17, min_weight: 51.1, max_weight: 55.0, belt_requirement: "1ST_POOM_ABOVE", registration_fee: 2500, max_participants: 64, display_order: 23, is_active: true },
  { code: "KY-JUN-M-U59", name: "Junior Male Under 59kg (Light)", discipline: "KYORUGI", division: "JUNIOR", gender: "MALE", min_age: 15, max_age: 17, min_weight: 55.1, max_weight: 59.0, belt_requirement: "1ST_POOM_ABOVE", registration_fee: 2500, max_participants: 64, display_order: 24, is_active: true },
  { code: "KY-JUN-M-U63", name: "Junior Male Under 63kg (Welter)", discipline: "KYORUGI", division: "JUNIOR", gender: "MALE", min_age: 15, max_age: 17, min_weight: 59.1, max_weight: 63.0, belt_requirement: "1ST_POOM_ABOVE", registration_fee: 2500, max_participants: 64, display_order: 25, is_active: true },
  { code: "KY-JUN-M-U68", name: "Junior Male Under 68kg (Light Middle)", discipline: "KYORUGI", division: "JUNIOR", gender: "MALE", min_age: 15, max_age: 17, min_weight: 63.1, max_weight: 68.0, belt_requirement: "1ST_POOM_ABOVE", registration_fee: 2500, max_participants: 64, display_order: 26, is_active: true },
  { code: "KY-JUN-M-U73", name: "Junior Male Under 73kg (Middle)", discipline: "KYORUGI", division: "JUNIOR", gender: "MALE", min_age: 15, max_age: 17, min_weight: 68.1, max_weight: 73.0, belt_requirement: "1ST_POOM_ABOVE", registration_fee: 2500, max_participants: 64, display_order: 27, is_active: true },
  { code: "KY-JUN-M-U78", name: "Junior Male Under 78kg (Light Heavy)", discipline: "KYORUGI", division: "JUNIOR", gender: "MALE", min_age: 15, max_age: 17, min_weight: 73.1, max_weight: 78.0, belt_requirement: "1ST_POOM_ABOVE", registration_fee: 2500, max_participants: 64, display_order: 28, is_active: true },
  { code: "KY-JUN-M-O78", name: "Junior Male Over 78kg (+78kg Heavy)", discipline: "KYORUGI", division: "JUNIOR", gender: "MALE", min_age: 15, max_age: 17, min_weight: 78.1, max_weight: 120.0, belt_requirement: "1ST_POOM_ABOVE", registration_fee: 2500, max_participants: 64, display_order: 29, is_active: true },

  // ----------------------------------------------------------------------------
  // KYORUGI (SPARRING) - JUNIOR FEMALE (Age 15-17) - Official World Taekwondo
  // ----------------------------------------------------------------------------
  { code: "KY-JUN-F-U42", name: "Junior Female Under 42kg (Fin)", discipline: "KYORUGI", division: "JUNIOR", gender: "FEMALE", min_age: 15, max_age: 17, min_weight: 32.0, max_weight: 42.0, belt_requirement: "1ST_POOM_ABOVE", registration_fee: 2500, max_participants: 64, display_order: 30, is_active: true },
  { code: "KY-JUN-F-U44", name: "Junior Female Under 44kg (Fly)", discipline: "KYORUGI", division: "JUNIOR", gender: "FEMALE", min_age: 15, max_age: 17, min_weight: 42.1, max_weight: 44.0, belt_requirement: "1ST_POOM_ABOVE", registration_fee: 2500, max_participants: 64, display_order: 31, is_active: true },
  { code: "KY-JUN-F-U46", name: "Junior Female Under 46kg (Bantam)", discipline: "KYORUGI", division: "JUNIOR", gender: "FEMALE", min_age: 15, max_age: 17, min_weight: 44.1, max_weight: 46.0, belt_requirement: "1ST_POOM_ABOVE", registration_fee: 2500, max_participants: 64, display_order: 32, is_active: true },
  { code: "KY-JUN-F-U49", name: "Junior Female Under 49kg (Feather)", discipline: "KYORUGI", division: "JUNIOR", gender: "FEMALE", min_age: 15, max_age: 17, min_weight: 46.1, max_weight: 49.0, belt_requirement: "1ST_POOM_ABOVE", registration_fee: 2500, max_participants: 64, display_order: 33, is_active: true },
  { code: "KY-JUN-F-U52", name: "Junior Female Under 52kg (Light)", discipline: "KYORUGI", division: "JUNIOR", gender: "FEMALE", min_age: 15, max_age: 17, min_weight: 49.1, max_weight: 52.0, belt_requirement: "1ST_POOM_ABOVE", registration_fee: 2500, max_participants: 64, display_order: 34, is_active: true },
  { code: "KY-JUN-F-U55", name: "Junior Female Under 55kg (Welter)", discipline: "KYORUGI", division: "JUNIOR", gender: "FEMALE", min_age: 15, max_age: 17, min_weight: 52.1, max_weight: 55.0, belt_requirement: "1ST_POOM_ABOVE", registration_fee: 2500, max_participants: 64, display_order: 35, is_active: true },
  { code: "KY-JUN-F-U59", name: "Junior Female Under 59kg (Light Middle)", discipline: "KYORUGI", division: "JUNIOR", gender: "FEMALE", min_age: 15, max_age: 17, min_weight: 55.1, max_weight: 59.0, belt_requirement: "1ST_POOM_ABOVE", registration_fee: 2500, max_participants: 64, display_order: 36, is_active: true },
  { code: "KY-JUN-F-U63", name: "Junior Female Under 63kg (Middle)", discipline: "KYORUGI", division: "JUNIOR", gender: "FEMALE", min_age: 15, max_age: 17, min_weight: 59.1, max_weight: 63.0, belt_requirement: "1ST_POOM_ABOVE", registration_fee: 2500, max_participants: 64, display_order: 37, is_active: true },
  { code: "KY-JUN-F-U68", name: "Junior Female Under 68kg (Light Heavy)", discipline: "KYORUGI", division: "JUNIOR", gender: "FEMALE", min_age: 15, max_age: 17, min_weight: 63.1, max_weight: 68.0, belt_requirement: "1ST_POOM_ABOVE", registration_fee: 2500, max_participants: 64, display_order: 38, is_active: true },
  { code: "KY-JUN-F-O68", name: "Junior Female Over 68kg (+68kg Heavy)", discipline: "KYORUGI", division: "JUNIOR", gender: "FEMALE", min_age: 15, max_age: 17, min_weight: 68.1, max_weight: 105.0, belt_requirement: "1ST_POOM_ABOVE", registration_fee: 2500, max_participants: 64, display_order: 39, is_active: true },

  // ----------------------------------------------------------------------------
  // KYORUGI (SPARRING) - CADET MALE (Age 12-14) - Official World Taekwondo
  // ----------------------------------------------------------------------------
  { code: "KY-CAD-M-U33", name: "Cadet Male Under 33kg (Fin)", discipline: "KYORUGI", division: "CADET", gender: "MALE", min_age: 12, max_age: 14, min_weight: 25.0, max_weight: 33.0, belt_requirement: "COLOR_BELT_OR_POOM", registration_fee: 2500, max_participants: 64, display_order: 40, is_active: true },
  { code: "KY-CAD-M-U37", name: "Cadet Male Under 37kg (Fly)", discipline: "KYORUGI", division: "CADET", gender: "MALE", min_age: 12, max_age: 14, min_weight: 33.1, max_weight: 37.0, belt_requirement: "COLOR_BELT_OR_POOM", registration_fee: 2500, max_participants: 64, display_order: 41, is_active: true },
  { code: "KY-CAD-M-U41", name: "Cadet Male Under 41kg (Bantam)", discipline: "KYORUGI", division: "CADET", gender: "MALE", min_age: 12, max_age: 14, min_weight: 37.1, max_weight: 41.0, belt_requirement: "COLOR_BELT_OR_POOM", registration_fee: 2500, max_participants: 64, display_order: 42, is_active: true },
  { code: "KY-CAD-M-U45", name: "Cadet Male Under 45kg (Feather)", discipline: "KYORUGI", division: "CADET", gender: "MALE", min_age: 12, max_age: 14, min_weight: 41.1, max_weight: 45.0, belt_requirement: "COLOR_BELT_OR_POOM", registration_fee: 2500, max_participants: 64, display_order: 43, is_active: true },
  { code: "KY-CAD-M-U49", name: "Cadet Male Under 49kg (Light)", discipline: "KYORUGI", division: "CADET", gender: "MALE", min_age: 12, max_age: 14, min_weight: 45.1, max_weight: 49.0, belt_requirement: "COLOR_BELT_OR_POOM", registration_fee: 2500, max_participants: 64, display_order: 44, is_active: true },
  { code: "KY-CAD-M-U53", name: "Cadet Male Under 53kg (Welter)", discipline: "KYORUGI", division: "CADET", gender: "MALE", min_age: 12, max_age: 14, min_weight: 49.1, max_weight: 53.0, belt_requirement: "COLOR_BELT_OR_POOM", registration_fee: 2500, max_participants: 64, display_order: 45, is_active: true },
  { code: "KY-CAD-M-U57", name: "Cadet Male Under 57kg (Light Middle)", discipline: "KYORUGI", division: "CADET", gender: "MALE", min_age: 12, max_age: 14, min_weight: 53.1, max_weight: 57.0, belt_requirement: "COLOR_BELT_OR_POOM", registration_fee: 2500, max_participants: 64, display_order: 46, is_active: true },
  { code: "KY-CAD-M-U61", name: "Cadet Male Under 61kg (Middle)", discipline: "KYORUGI", division: "CADET", gender: "MALE", min_age: 12, max_age: 14, min_weight: 57.1, max_weight: 61.0, belt_requirement: "COLOR_BELT_OR_POOM", registration_fee: 2500, max_participants: 64, display_order: 47, is_active: true },
  { code: "KY-CAD-M-U65", name: "Cadet Male Under 65kg (Light Heavy)", discipline: "KYORUGI", division: "CADET", gender: "MALE", min_age: 12, max_age: 14, min_weight: 61.1, max_weight: 65.0, belt_requirement: "COLOR_BELT_OR_POOM", registration_fee: 2500, max_participants: 64, display_order: 48, is_active: true },
  { code: "KY-CAD-M-O65", name: "Cadet Male Over 65kg (+65kg Heavy)", discipline: "KYORUGI", division: "CADET", gender: "MALE", min_age: 12, max_age: 14, min_weight: 65.1, max_weight: 95.0, belt_requirement: "COLOR_BELT_OR_POOM", registration_fee: 2500, max_participants: 64, display_order: 49, is_active: true },

  // ----------------------------------------------------------------------------
  // KYORUGI (SPARRING) - CADET FEMALE (Age 12-14) - Official World Taekwondo
  // ----------------------------------------------------------------------------
  { code: "KY-CAD-F-U29", name: "Cadet Female Under 29kg (Fin)", discipline: "KYORUGI", division: "CADET", gender: "FEMALE", min_age: 12, max_age: 14, min_weight: 22.0, max_weight: 29.0, belt_requirement: "COLOR_BELT_OR_POOM", registration_fee: 2500, max_participants: 64, display_order: 50, is_active: true },
  { code: "KY-CAD-F-U33", name: "Cadet Female Under 33kg (Fly)", discipline: "KYORUGI", division: "CADET", gender: "FEMALE", min_age: 12, max_age: 14, min_weight: 29.1, max_weight: 33.0, belt_requirement: "COLOR_BELT_OR_POOM", registration_fee: 2500, max_participants: 64, display_order: 51, is_active: true },
  { code: "KY-CAD-F-U37", name: "Cadet Female Under 37kg (Bantam)", discipline: "KYORUGI", division: "CADET", gender: "FEMALE", min_age: 12, max_age: 14, min_weight: 33.1, max_weight: 37.0, belt_requirement: "COLOR_BELT_OR_POOM", registration_fee: 2500, max_participants: 64, display_order: 52, is_active: true },
  { code: "KY-CAD-F-U41", name: "Cadet Female Under 41kg (Feather)", discipline: "KYORUGI", division: "CADET", gender: "FEMALE", min_age: 12, max_age: 14, min_weight: 37.1, max_weight: 41.0, belt_requirement: "COLOR_BELT_OR_POOM", registration_fee: 2500, max_participants: 64, display_order: 53, is_active: true },
  { code: "KY-CAD-F-U44", name: "Cadet Female Under 44kg (Light)", discipline: "KYORUGI", division: "CADET", gender: "FEMALE", min_age: 12, max_age: 14, min_weight: 41.1, max_weight: 44.0, belt_requirement: "COLOR_BELT_OR_POOM", registration_fee: 2500, max_participants: 64, display_order: 54, is_active: true },
  { code: "KY-CAD-F-U47", name: "Cadet Female Under 47kg (Welter)", discipline: "KYORUGI", division: "CADET", gender: "FEMALE", min_age: 12, max_age: 14, min_weight: 44.1, max_weight: 47.0, belt_requirement: "COLOR_BELT_OR_POOM", registration_fee: 2500, max_participants: 64, display_order: 55, is_active: true },
  { code: "KY-CAD-F-U51", name: "Cadet Female Under 51kg (Light Middle)", discipline: "KYORUGI", division: "CADET", gender: "FEMALE", min_age: 12, max_age: 14, min_weight: 47.1, max_weight: 51.0, belt_requirement: "COLOR_BELT_OR_POOM", registration_fee: 2500, max_participants: 64, display_order: 56, is_active: true },
  { code: "KY-CAD-F-U55", name: "Cadet Female Under 55kg (Middle)", discipline: "KYORUGI", division: "CADET", gender: "FEMALE", min_age: 12, max_age: 14, min_weight: 51.1, max_weight: 55.0, belt_requirement: "COLOR_BELT_OR_POOM", registration_fee: 2500, max_participants: 64, display_order: 57, is_active: true },
  { code: "KY-CAD-F-U59", name: "Cadet Female Under 59kg (Light Heavy)", discipline: "KYORUGI", division: "CADET", gender: "FEMALE", min_age: 12, max_age: 14, min_weight: 55.1, max_weight: 59.0, belt_requirement: "COLOR_BELT_OR_POOM", registration_fee: 2500, max_participants: 64, display_order: 58, is_active: true },
  { code: "KY-CAD-F-O59", name: "Cadet Female Over 59kg (+59kg Heavy)", discipline: "KYORUGI", division: "CADET", gender: "FEMALE", min_age: 12, max_age: 14, min_weight: 59.1, max_weight: 85.0, belt_requirement: "COLOR_BELT_OR_POOM", registration_fee: 2500, max_participants: 64, display_order: 59, is_active: true },

  // ----------------------------------------------------------------------------
  // KYORUGI (SPARRING) - SUB-JUNIOR (Age 5-11) - Kukkiwon Standard
  // ----------------------------------------------------------------------------
  { code: "KY-SUB-M-U18", name: "Sub-Junior Male Under 18kg", discipline: "KYORUGI", division: "SUB_JUNIOR", gender: "MALE", min_age: 5, max_age: 11, min_weight: 12.0, max_weight: 18.0, belt_requirement: "COLOR_BELT_OR_POOM", registration_fee: 2500, max_participants: 64, display_order: 60, is_active: true },
  { code: "KY-SUB-M-U21", name: "Sub-Junior Male Under 21kg", discipline: "KYORUGI", division: "SUB_JUNIOR", gender: "MALE", min_age: 5, max_age: 11, min_weight: 18.1, max_weight: 21.0, belt_requirement: "COLOR_BELT_OR_POOM", registration_fee: 2500, max_participants: 64, display_order: 61, is_active: true },
  { code: "KY-SUB-M-U24", name: "Sub-Junior Male Under 24kg", discipline: "KYORUGI", division: "SUB_JUNIOR", gender: "MALE", min_age: 5, max_age: 11, min_weight: 21.1, max_weight: 24.0, belt_requirement: "COLOR_BELT_OR_POOM", registration_fee: 2500, max_participants: 64, display_order: 62, is_active: true },
  { code: "KY-SUB-M-U27", name: "Sub-Junior Male Under 27kg", discipline: "KYORUGI", division: "SUB_JUNIOR", gender: "MALE", min_age: 5, max_age: 11, min_weight: 24.1, max_weight: 27.0, belt_requirement: "COLOR_BELT_OR_POOM", registration_fee: 2500, max_participants: 64, display_order: 63, is_active: true },
  { code: "KY-SUB-M-U30", name: "Sub-Junior Male Under 30kg", discipline: "KYORUGI", division: "SUB_JUNIOR", gender: "MALE", min_age: 5, max_age: 11, min_weight: 27.1, max_weight: 30.0, belt_requirement: "COLOR_BELT_OR_POOM", registration_fee: 2500, max_participants: 64, display_order: 64, is_active: true },
  { code: "KY-SUB-M-U33", name: "Sub-Junior Male Under 33kg", discipline: "KYORUGI", division: "SUB_JUNIOR", gender: "MALE", min_age: 5, max_age: 11, min_weight: 30.1, max_weight: 33.0, belt_requirement: "COLOR_BELT_OR_POOM", registration_fee: 2500, max_participants: 64, display_order: 65, is_active: true },
  { code: "KY-SUB-M-U36", name: "Sub-Junior Male Under 36kg", discipline: "KYORUGI", division: "SUB_JUNIOR", gender: "MALE", min_age: 5, max_age: 11, min_weight: 33.1, max_weight: 36.0, belt_requirement: "COLOR_BELT_OR_POOM", registration_fee: 2500, max_participants: 64, display_order: 66, is_active: true },
  { code: "KY-SUB-M-U40", name: "Sub-Junior Male Under 40kg", discipline: "KYORUGI", division: "SUB_JUNIOR", gender: "MALE", min_age: 5, max_age: 11, min_weight: 36.1, max_weight: 40.0, belt_requirement: "COLOR_BELT_OR_POOM", registration_fee: 2500, max_participants: 64, display_order: 67, is_active: true },
  { code: "KY-SUB-M-O40", name: "Sub-Junior Male Over 40kg (+40kg)", discipline: "KYORUGI", division: "SUB_JUNIOR", gender: "MALE", min_age: 5, max_age: 11, min_weight: 40.1, max_weight: 70.0, belt_requirement: "COLOR_BELT_OR_POOM", registration_fee: 2500, max_participants: 64, display_order: 68, is_active: true },

  { code: "KY-SUB-F-U18", name: "Sub-Junior Female Under 18kg", discipline: "KYORUGI", division: "SUB_JUNIOR", gender: "FEMALE", min_age: 5, max_age: 11, min_weight: 12.0, max_weight: 18.0, belt_requirement: "COLOR_BELT_OR_POOM", registration_fee: 2500, max_participants: 64, display_order: 70, is_active: true },
  { code: "KY-SUB-F-U21", name: "Sub-Junior Female Under 21kg", discipline: "KYORUGI", division: "SUB_JUNIOR", gender: "FEMALE", min_age: 5, max_age: 11, min_weight: 18.1, max_weight: 21.0, belt_requirement: "COLOR_BELT_OR_POOM", registration_fee: 2500, max_participants: 64, display_order: 71, is_active: true },
  { code: "KY-SUB-F-U24", name: "Sub-Junior Female Under 24kg", discipline: "KYORUGI", division: "SUB_JUNIOR", gender: "FEMALE", min_age: 5, max_age: 11, min_weight: 21.1, max_weight: 24.0, belt_requirement: "COLOR_BELT_OR_POOM", registration_fee: 2500, max_participants: 64, display_order: 72, is_active: true },
  { code: "KY-SUB-F-U27", name: "Sub-Junior Female Under 27kg", discipline: "KYORUGI", division: "SUB_JUNIOR", gender: "FEMALE", min_age: 5, max_age: 11, min_weight: 24.1, max_weight: 27.0, belt_requirement: "COLOR_BELT_OR_POOM", registration_fee: 2500, max_participants: 64, display_order: 73, is_active: true },
  { code: "KY-SUB-F-U30", name: "Sub-Junior Female Under 30kg", discipline: "KYORUGI", division: "SUB_JUNIOR", gender: "FEMALE", min_age: 5, max_age: 11, min_weight: 27.1, max_weight: 30.0, belt_requirement: "COLOR_BELT_OR_POOM", registration_fee: 2500, max_participants: 64, display_order: 74, is_active: true },
  { code: "KY-SUB-F-U33", name: "Sub-Junior Female Under 33kg", discipline: "KYORUGI", division: "SUB_JUNIOR", gender: "FEMALE", min_age: 5, max_age: 11, min_weight: 30.1, max_weight: 33.0, belt_requirement: "COLOR_BELT_OR_POOM", registration_fee: 2500, max_participants: 64, display_order: 75, is_active: true },
  { code: "KY-SUB-F-U36", name: "Sub-Junior Female Under 36kg", discipline: "KYORUGI", division: "SUB_JUNIOR", gender: "FEMALE", min_age: 5, max_age: 11, min_weight: 33.1, max_weight: 36.0, belt_requirement: "COLOR_BELT_OR_POOM", registration_fee: 2500, max_participants: 64, display_order: 76, is_active: true },
  { code: "KY-SUB-F-U40", name: "Sub-Junior Female Under 40kg", discipline: "KYORUGI", division: "SUB_JUNIOR", gender: "FEMALE", min_age: 5, max_age: 11, min_weight: 36.1, max_weight: 40.0, belt_requirement: "COLOR_BELT_OR_POOM", registration_fee: 2500, max_participants: 64, display_order: 77, is_active: true },
  { code: "KY-SUB-F-O40", name: "Sub-Junior Female Over 40kg (+40kg)", discipline: "KYORUGI", division: "SUB_JUNIOR", gender: "FEMALE", min_age: 5, max_age: 11, min_weight: 40.1, max_weight: 70.0, belt_requirement: "COLOR_BELT_OR_POOM", registration_fee: 2500, max_participants: 64, display_order: 78, is_active: true },

  // ----------------------------------------------------------------------------
  // POOMSAE (FORMS)
  // ----------------------------------------------------------------------------
  {
    code: "PO-IND-SEN-M",
    name: "Individual Senior Male Poomsae",
    discipline: "POOMSAE",
    division: "SENIOR",
    gender: "MALE",
    min_age: 18,
    max_age: 65,
    belt_requirement: "1ST_DAN_ABOVE",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 80,
    is_active: true,
  },
  {
    code: "PO-IND-SEN-F",
    name: "Individual Senior Female Poomsae",
    discipline: "POOMSAE",
    division: "SENIOR",
    gender: "FEMALE",
    min_age: 18,
    max_age: 65,
    belt_requirement: "1ST_DAN_ABOVE",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 81,
    is_active: true,
  },
  {
    code: "PO-IND-JUN-M",
    name: "Individual Junior Male Poomsae",
    discipline: "POOMSAE",
    division: "JUNIOR",
    gender: "MALE",
    min_age: 15,
    max_age: 17,
    belt_requirement: "1ST_POOM_ABOVE",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 82,
    is_active: true,
  },
  {
    code: "PO-IND-JUN-F",
    name: "Individual Junior Female Poomsae",
    discipline: "POOMSAE",
    division: "JUNIOR",
    gender: "FEMALE",
    min_age: 15,
    max_age: 17,
    belt_requirement: "1ST_POOM_ABOVE",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 83,
    is_active: true,
  },
  {
    code: "PO-IND-CAD-M",
    name: "Individual Cadet Male Poomsae",
    discipline: "POOMSAE",
    division: "CADET",
    gender: "MALE",
    min_age: 12,
    max_age: 14,
    belt_requirement: "COLOR_BELT_OR_POOM",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 84,
    is_active: true,
  },
  {
    code: "PO-IND-CAD-F",
    name: "Individual Cadet Female Poomsae",
    discipline: "POOMSAE",
    division: "CADET",
    gender: "FEMALE",
    min_age: 12,
    max_age: 14,
    belt_requirement: "COLOR_BELT_OR_POOM",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 85,
    is_active: true,
  },
  {
    code: "PO-IND-SUB-ALL",
    name: "Sub-Junior Poomsae (Boys & Girls)",
    discipline: "POOMSAE",
    division: "SUB_JUNIOR",
    gender: "OTHER",
    min_age: 5,
    max_age: 11,
    belt_requirement: "COLOR_BELT_OR_POOM",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 86,
    is_active: true,
  },
  {
    code: "PO-COLOR-OPEN",
    name: "Color Belt Poomsae (All Ages, Geup 8-1)",
    discipline: "POOMSAE",
    division: "OPEN",
    gender: "OTHER",
    min_age: 5,
    max_age: 65,
    belt_requirement: "COLOR_BELT",
    registration_fee: 2500,
    max_participants: 128,
    display_order: 87,
    is_active: true,
  },

  // ----------------------------------------------------------------------------
  // BREAKING (KYUKPA & POWER BREAKING)
  // ----------------------------------------------------------------------------
  {
    code: "DM-TEAM-OPEN",
    name: "Championship Team Breaking (Open)",
    discipline: "DEMO",
    division: "OPEN",
    gender: "OTHER",
    min_age: 8,
    max_age: 65,
    belt_requirement: "ANY",
    registration_fee: 5000,
    max_participants: 32,
    display_order: 90,
    is_active: true,
  },
  {
    code: "DM-KYUKPA-HIGH",
    name: "High Jump & Kyukpa Power Breaking",
    discipline: "DEMO",
    division: "SENIOR",
    gender: "OTHER",
    min_age: 16,
    max_age: 65,
    belt_requirement: "1ST_DAN_ABOVE",
    registration_fee: 2500,
    max_participants: 32,
    display_order: 91,
    is_active: true,
  },
];
