// ==============================================================================
// OFFICIAL CHAMPIONSHIP CATEGORY CONFIGURATION
// Kukkiwon North India x Kyorix Sports Technology Standards
// ==============================================================================

import { Category } from "@/types/registration";

export const INITIAL_CATEGORIES: Omit<Category, "id" | "championship_id">[] = [
  // ----------------------------------------------------------------------------
  // KYORUGI (SPARRING) - SENIOR (Age 17+)
  // ----------------------------------------------------------------------------
  {
    code: "KY-SEN-M-U58",
    name: "Senior Male -58kg (Flyweight)",
    discipline: "KYORUGI",
    division: "SENIOR",
    gender: "MALE",
    min_age: 17,
    max_age: 45,
    min_weight: 45.0,
    max_weight: 58.0,
    belt_requirement: "1ST_DAN_ABOVE",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 10,
    is_active: true,
  },
  {
    code: "KY-SEN-M-U68",
    name: "Senior Male -68kg (Featherweight)",
    discipline: "KYORUGI",
    division: "SENIOR",
    gender: "MALE",
    min_age: 17,
    max_age: 45,
    min_weight: 58.1,
    max_weight: 68.0,
    belt_requirement: "1ST_DAN_ABOVE",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 11,
    is_active: true,
  },
  {
    code: "KY-SEN-M-U80",
    name: "Senior Male -80kg (Welterweight)",
    discipline: "KYORUGI",
    division: "SENIOR",
    gender: "MALE",
    min_age: 17,
    max_age: 45,
    min_weight: 68.1,
    max_weight: 80.0,
    belt_requirement: "1ST_DAN_ABOVE",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 12,
    is_active: true,
  },
  {
    code: "KY-SEN-M-O80",
    name: "Senior Male +80kg (Heavyweight)",
    discipline: "KYORUGI",
    division: "SENIOR",
    gender: "MALE",
    min_age: 17,
    max_age: 45,
    min_weight: 80.1,
    max_weight: 140.0,
    belt_requirement: "1ST_DAN_ABOVE",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 13,
    is_active: true,
  },
  {
    code: "KY-SEN-F-U49",
    name: "Senior Female -49kg (Flyweight)",
    discipline: "KYORUGI",
    division: "SENIOR",
    gender: "FEMALE",
    min_age: 17,
    max_age: 45,
    min_weight: 40.0,
    max_weight: 49.0,
    belt_requirement: "1ST_DAN_ABOVE",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 20,
    is_active: true,
  },
  {
    code: "KY-SEN-F-U57",
    name: "Senior Female -57kg (Featherweight)",
    discipline: "KYORUGI",
    division: "SENIOR",
    gender: "FEMALE",
    min_age: 17,
    max_age: 45,
    min_weight: 49.1,
    max_weight: 57.0,
    belt_requirement: "1ST_DAN_ABOVE",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 21,
    is_active: true,
  },
  {
    code: "KY-SEN-F-U67",
    name: "Senior Female -67kg (Welterweight)",
    discipline: "KYORUGI",
    division: "SENIOR",
    gender: "FEMALE",
    min_age: 17,
    max_age: 45,
    min_weight: 57.1,
    max_weight: 67.0,
    belt_requirement: "1ST_DAN_ABOVE",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 22,
    is_active: true,
  },
  {
    code: "KY-SEN-F-O67",
    name: "Senior Female +67kg (Heavyweight)",
    discipline: "KYORUGI",
    division: "SENIOR",
    gender: "FEMALE",
    min_age: 17,
    max_age: 45,
    min_weight: 67.1,
    max_weight: 120.0,
    belt_requirement: "1ST_DAN_ABOVE",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 23,
    is_active: true,
  },

  // ----------------------------------------------------------------------------
  // KYORUGI (SPARRING) - JUNIOR (Age 15-17)
  // ----------------------------------------------------------------------------
  {
    code: "KY-JUN-M-U48",
    name: "Junior Male -48kg",
    discipline: "KYORUGI",
    division: "JUNIOR",
    gender: "MALE",
    min_age: 15,
    max_age: 17,
    min_weight: 40.0,
    max_weight: 48.0,
    belt_requirement: "1ST_POOM_ABOVE",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 30,
    is_active: true,
  },
  {
    code: "KY-JUN-M-U55",
    name: "Junior Male -55kg",
    discipline: "KYORUGI",
    division: "JUNIOR",
    gender: "MALE",
    min_age: 15,
    max_age: 17,
    min_weight: 48.1,
    max_weight: 55.0,
    belt_requirement: "1ST_POOM_ABOVE",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 31,
    is_active: true,
  },
  {
    code: "KY-JUN-M-U63",
    name: "Junior Male -63kg",
    discipline: "KYORUGI",
    division: "JUNIOR",
    gender: "MALE",
    min_age: 15,
    max_age: 17,
    min_weight: 55.1,
    max_weight: 63.0,
    belt_requirement: "1ST_POOM_ABOVE",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 32,
    is_active: true,
  },
  {
    code: "KY-JUN-M-O73",
    name: "Junior Male +73kg",
    discipline: "KYORUGI",
    division: "JUNIOR",
    gender: "MALE",
    min_age: 15,
    max_age: 17,
    min_weight: 73.1,
    max_weight: 120.0,
    belt_requirement: "1ST_POOM_ABOVE",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 33,
    is_active: true,
  },
  {
    code: "KY-JUN-F-U44",
    name: "Junior Female -44kg",
    discipline: "KYORUGI",
    division: "JUNIOR",
    gender: "FEMALE",
    min_age: 15,
    max_age: 17,
    min_weight: 38.0,
    max_weight: 44.0,
    belt_requirement: "1ST_POOM_ABOVE",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 40,
    is_active: true,
  },
  {
    code: "KY-JUN-F-U49",
    name: "Junior Female -49kg",
    discipline: "KYORUGI",
    division: "JUNIOR",
    gender: "FEMALE",
    min_age: 15,
    max_age: 17,
    min_weight: 44.1,
    max_weight: 49.0,
    belt_requirement: "1ST_POOM_ABOVE",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 41,
    is_active: true,
  },
  {
    code: "KY-JUN-F-U55",
    name: "Junior Female -55kg",
    discipline: "KYORUGI",
    division: "JUNIOR",
    gender: "FEMALE",
    min_age: 15,
    max_age: 17,
    min_weight: 49.1,
    max_weight: 55.0,
    belt_requirement: "1ST_POOM_ABOVE",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 42,
    is_active: true,
  },
  {
    code: "KY-JUN-F-O63",
    name: "Junior Female +63kg",
    discipline: "KYORUGI",
    division: "JUNIOR",
    gender: "FEMALE",
    min_age: 15,
    max_age: 17,
    min_weight: 63.1,
    max_weight: 100.0,
    belt_requirement: "1ST_POOM_ABOVE",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 43,
    is_active: true,
  },

  // ----------------------------------------------------------------------------
  // KYORUGI (SPARRING) - CADET (Age 12-14)
  // ----------------------------------------------------------------------------
  {
    code: "KY-CAD-M-U37",
    name: "Cadet Male -37kg",
    discipline: "KYORUGI",
    division: "CADET",
    gender: "MALE",
    min_age: 12,
    max_age: 14,
    min_weight: 30.0,
    max_weight: 37.0,
    belt_requirement: "COLOR_BELT_OR_POOM",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 50,
    is_active: true,
  },
  {
    code: "KY-CAD-M-U45",
    name: "Cadet Male -45kg",
    discipline: "KYORUGI",
    division: "CADET",
    gender: "MALE",
    min_age: 12,
    max_age: 14,
    min_weight: 37.1,
    max_weight: 45.0,
    belt_requirement: "COLOR_BELT_OR_POOM",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 51,
    is_active: true,
  },
  {
    code: "KY-CAD-F-U37",
    name: "Cadet Female -37kg",
    discipline: "KYORUGI",
    division: "CADET",
    gender: "FEMALE",
    min_age: 12,
    max_age: 14,
    min_weight: 30.0,
    max_weight: 37.0,
    belt_requirement: "COLOR_BELT_OR_POOM",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 52,
    is_active: true,
  },
  {
    code: "KY-CAD-F-U44",
    name: "Cadet Female -44kg",
    discipline: "KYORUGI",
    division: "CADET",
    gender: "FEMALE",
    min_age: 12,
    max_age: 14,
    min_weight: 37.1,
    max_weight: 44.0,
    belt_requirement: "COLOR_BELT_OR_POOM",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 53,
    is_active: true,
  },

  // ----------------------------------------------------------------------------
  // KYORUGI (SPARRING) - SUB-JUNIOR (Age 8-11)
  // ----------------------------------------------------------------------------
  {
    code: "KY-SUB-M-OPEN",
    name: "Sub-Junior Male Open Group",
    discipline: "KYORUGI",
    division: "SUB_JUNIOR",
    gender: "MALE",
    min_age: 8,
    max_age: 11,
    min_weight: 20.0,
    max_weight: 55.0,
    belt_requirement: "COLOR_BELT_OR_POOM",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 60,
    is_active: true,
  },
  {
    code: "KY-SUB-F-OPEN",
    name: "Sub-Junior Female Open Group",
    discipline: "KYORUGI",
    division: "SUB_JUNIOR",
    gender: "FEMALE",
    min_age: 8,
    max_age: 11,
    min_weight: 20.0,
    max_weight: 55.0,
    belt_requirement: "COLOR_BELT_OR_POOM",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 61,
    is_active: true,
  },

  // ----------------------------------------------------------------------------
  // POOMSAE (FORMS)
  // ----------------------------------------------------------------------------
  {
    code: "PO-IND-SEN-M",
    name: "Individual Senior Male Poomsae",
    discipline: "POOMSAE",
    division: "SENIOR",
    gender: "MALE",
    min_age: 18,
    max_age: 35,
    belt_requirement: "1ST_DAN_ABOVE",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 70,
    is_active: true,
  },
  {
    code: "PO-IND-SEN-F",
    name: "Individual Senior Female Poomsae",
    discipline: "POOMSAE",
    division: "SENIOR",
    gender: "FEMALE",
    min_age: 18,
    max_age: 35,
    belt_requirement: "1ST_DAN_ABOVE",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 71,
    is_active: true,
  },
  {
    code: "PO-IND-JUN-M",
    name: "Individual Junior Male Poomsae",
    discipline: "POOMSAE",
    division: "JUNIOR",
    gender: "MALE",
    min_age: 15,
    max_age: 17,
    belt_requirement: "1ST_POOM_ABOVE",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 72,
    is_active: true,
  },
  {
    code: "PO-IND-JUN-F",
    name: "Individual Junior Female Poomsae",
    discipline: "POOMSAE",
    division: "JUNIOR",
    gender: "FEMALE",
    min_age: 15,
    max_age: 17,
    belt_requirement: "1ST_POOM_ABOVE",
    registration_fee: 2500,
    max_participants: 64,
    display_order: 73,
    is_active: true,
  },
  {
    code: "PO-COLOR-OPEN",
    name: "Color Belt Poomsae (All Ages, Geup 8-1)",
    discipline: "POOMSAE",
    division: "OPEN",
    gender: "MALE", // Open to all, validated flexibly
    min_age: 6,
    max_age: 60,
    belt_requirement: "COLOR_BELT",
    registration_fee: 2500,
    max_participants: 128,
    display_order: 74,
    is_active: true,
  },

  // ----------------------------------------------------------------------------
  // DEMO (DEMONSTRATION & KYUKPA)
  // ----------------------------------------------------------------------------
  {
    code: "DM-TEAM-OPEN",
    name: "Championship Team Demonstration (Open)",
    discipline: "DEMO",
    division: "OPEN",
    gender: "MALE", // Open
    min_age: 10,
    max_age: 50,
    belt_requirement: "ANY",
    registration_fee: 5000,
    max_participants: 32,
    display_order: 80,
    is_active: true,
  },
  {
    code: "DM-KYUKPA-HIGH",
    name: "High Jump & Kyukpa Power Breaking",
    discipline: "DEMO",
    division: "SENIOR",
    gender: "MALE",
    min_age: 16,
    max_age: 45,
    belt_requirement: "1ST_DAN_ABOVE",
    registration_fee: 2500,
    max_participants: 32,
    display_order: 81,
    is_active: true,
  },
];
